### ISSUE TITLE
bottomPanel configuration doesn't work anymore?

### ISSUE THREAD

**Issue by dicksonlaw583** [IIIF/mirador#1095]
See the Zen mode setup on the Wiki's "Configuration Guides" page: https://github.com/IIIF/mirador/wiki/Configuration-Guides#zen-mode

The `bottomPanel : false` setting there no longer hides the bottom panel on any 2.1.0 release candidate. It seems that I have to add `bottomPanelAvailable: false` and `bottomPanelvisible: false` on top of that to make it go away now. Should this be happening?

**Comment by rsinghal** [comment]
`bottomPanel : false` will make that panel completely unavailable.
`bottomPanelVisible: false` will create the panel, but have it minimized by default.

Now fixed in the latest release2.1

**Comment by brutaldigital** [comment]
Hi @rsinghal 
I'm still experiencing this issue in release2.1 as well as with other configurables in windowObjects. The following have no effect:

`sidePanel : false`
`bottomPanel : false`
`overlay : false`
`layoutOptions.close : false`
